name: legacyhalos
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - fitsio
  - scipy
  - numpy
  - matplotlib
  - astropy
  - astrometry
  - ipykernel
  - seaborn
  - h5py
  - pydl
  - pyyaml
  - corner
  - scikit-image
  - gnureadline
  - mpi4py
  - pip
  - pip:
    - colossus
