name: legacyhalos
channels:
  - conda-forge
dependencies:
  - python=3.10
  - fitsio
  - scipy
  - numpy
  - matplotlib
  - astropy
  - astrometry
  - photutils
  - ipykernel
  - seaborn
  - h5py
  - pydl
  - pyyaml
  - corner
  - scikit-image
  - mpi4py
  - coveralls
  - pytest
  - black
  - flake8
  - pip
  - pip:
    - colossus
